src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>嘉定区</fullName>
                </value>
                <value>
                    <fullName>浦东区</fullName>
                </value>
                <value>
                    <fullName>哈尔滨市</fullName>
                </value>
                <value>
                    <fullName>绥化市</fullName>
                </value>
                <value>
                    <fullName>朝阳区</fullName>
                </value>
                <value>
                    <fullName>苏州市</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>上海市</fullName>
                </value>
                <value>
                    <fullName>北京市</fullName>
                </value>
                <value>
                    <fullName>黑龙江省</fullName>
                </value>
                <value>
                    <fullName>江苏省</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ClsService_Picklist_Test.cls
@isTest
public with sharing class ClsService_Picklist_Test {
    static testMethod void test_getEntries() {
        
        List<Map<String,String>> picklistEntry_List = ClsService_Picklist.getEntries('Account', 'AccountSource');
        Boolean result = false;
        for (Map<String,String> obj : picklistEntry_List) {
        	if (obj.get('label') == 'Web') {
        		result = true;
        	}
        }
        System.assertEquals(true, result);
        

    }

    static testMethod void test_getDependentEntries() {
        
           Map<String, List<Map<String,String>>> result_Map = ClsService_Picklist.getDependentEntries('Account', 'Province__c', 'City__c'); 
        
    }

}