src/objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Department</relationshipLabel>
        <relationshipName>Department</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Department</relationshipLabel>
        <relationshipName>Department</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Employee</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LC_DepartmentController.cls
/**
 * Created by meixing on 2019-10-05.
 */

public with sharing class LC_DepartmentController {

    @AuraEnabled
    public static List<Department__c> getEmployeeDepartments(String employeeId) {
        List<Department__c> allRelatedDepartments = new List<Department__c>();
        Set<String> allRelatedDepartmentIds = new Set<String>();

        for (Employee__c employee : [SELECT Department__c, Department__r.Parent__c FROM Employee__c WHERE Id = :employeeId]) {
            allRelatedDepartmentIds.add(employee.Department__c);
            allRelatedDepartmentIds.add(employee.Department__r.Parent__c);
        }

        for (Department__c department : [SELECT Id, Name, Parent__c, PrimaryContact__c, PrimaryContact__r.Name, PrimaryContact__r.Phone__c
                                         FROM Department__c
                                         WHERE Id IN :allRelatedDepartmentIds]) {
            allRelatedDepartments.add(department);
        }

        return allRelatedDepartments;
    }



}