src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Experience__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Experience</label>
        <referenceTo>Experience__c</referenceTo>
        <relationshipLabel>Employee</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SelfDescription__c</fullName>
        <label>Self Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SkillDescription__c</fullName>
        <label>Skill Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Experience__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Experience (Employee)</relationshipLabel>
        <relationshipName>ExperienceTest</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelatedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedTo</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Experience</relationshipLabel>
        <relationshipName>Experience</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LC_EmployeeController.cls
public with sharing class LC_EmployeeController {
	@AuraEnabled
    public static List<Employee__c> getEmployeeDetails(String employeeId) {
        List<Employee__c> results = [SELECT Id, SelfDescription__c, SkillDescription__c FROM Employee__c 
                                     WHERE Id = : employeeId];
        return results;
    }


    @AuraEnabled
    public static List<Experience__c>  updateExperiencesList(String  experienceList, String employeeId, String recordType) {
            System.debug('RecordType----------->' + recordType);
            List<Experience__c> resultList = new List<Experience__c> ();
            List <Experience__c> experienceListUpdate = (List<Experience__c>) System.JSON.deserialize(experienceList, List<Experience__c>.Class);
            System.debug('experienceList---------->' + experienceListUpdate);
            //Employee__c targetEmployee =[SELECT Id, Name FROM Employee__c WHERE Id =: employeeId];
            RecordType targetRecordType = [SELECT Id, DeveloperName FROM RecordType WHERE RecordType.DeveloperName =: recordType];
            for (Experience__c e : experienceListUpdate) {
                e.RelatedTo__c = employeeId;
                e.RecordTypeId = targetRecordType.Id;
            }
            upsert experienceListUpdate; 
            return experienceListUpdate;
       
        
    }
}